# Generated by Django 5.1.1 on 2024-10-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_remove_deal_category_deal_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.dealscategory'),
        ),
    ]
